name: 'SemVer tags from PR labels'
description: 'This action creates SemVer tags from PR labels'
author: 'VSHN AG'

inputs:
  patch-label:
    description: 'Label which indicates a patch-level SemVer bump'
    required: false
    default: 'bump:patch'
  minor-label:
    description: 'Label which indicates a minor-level SemVer bump'
    required: false
    default: 'bump:minor'
  major-label:
    description: 'Label which indicates a major-level SemVer bump'
    required: false
    default: 'bump:major'

runs:
  using: node20
  main: dist/index.js
